version: '3'
services:
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - "./data:/data/db"
  app:
    image: "jaykravetz/docker-mongo-talk:latest"
    links:
      - "mongo:mongo"
    ports:
      - "8080:8080"
    volumes:
      - ".:/var/apps/current"